# Generated by Django 2.2.16 on 2022-09-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='/img/user/user.png', upload_to='users/', verbose_name='Аватар'),
        ),
    ]
